<a href="https://colab.research.google.com/github/ajkc-dev/DL-TF-Keras-01/blob/main/TensorFlow_2_quickstart_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Set up TensorFlow**  
Import TensorFlow into your program to get started:

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


**Load a dataset**  
Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


[Build a machine learning model](https://www.tensorflow.org/tutorials/quickstart/beginner?_gl=1*1nkl9ju*_up*MQ..*_ga*MTM1MDMyMzg5LjE3NTIwNjc4Mzg.*_ga_W0YLR4190T*czE3NTIwNjc4MzgkbzEkZzAkdDE3NTIwNjc4MzgkajYwJGwwJGgw#build_a_machine_learning_model)  
Build a tf.keras.Sequential model:

Sequential is useful for stacking layers where each layer has one input tensor and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the Flatten, Dense, and Dropout layers.

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


For each example, the model returns a vector of logits or log-odds scores, one for each class.

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.2612087 ,  0.17325959, -0.2896306 ,  1.035263  , -0.00676847,
         0.17006314, -0.16798033,  0.3411149 ,  0.29088563,  0.4827162 ]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.05964246, 0.0920964 , 0.05797116, 0.21807504, 0.07692322,
        0.09180249, 0.06547026, 0.10892843, 0.10359219, 0.12549834]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy:

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [7]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.388116)

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

**[Train and evaluate your model](https://www.tensorflow.org/tutorials/quickstart/beginner?_gl=1*1nkl9ju*_up*MQ..*_ga*MTM1MDMyMzg5LjE3NTIwNjc4Mzg.*_ga_W0YLR4190T*czE3NTIwNjc4MzgkbzEkZzAkdDE3NTIwNjc4MzgkajYwJGwwJGgw#train_and_evaluate_your_model)**

Use the Model.fit method to adjust your model parameters and minimize the loss:

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8644 - loss: 0.4735
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9533 - loss: 0.1552
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9674 - loss: 0.1081
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9730 - loss: 0.0893
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9763 - loss: 0.0768


The Model.evaluate method checks the model's performance, usually on a validation set or test set.

In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 2ms/step - accuracy: 0.9767 - loss: 0.0760


[0.07600484788417816, 0.9767000079154968]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.2633307e-08, 5.5712381e-09, 1.0520853e-05, 2.2350939e-04,
        2.7638371e-11, 5.2572684e-08, 3.1151533e-13, 9.9976462e-01,
        4.1779887e-07, 8.5420811e-07],
       [8.9489456e-09, 7.5159871e-05, 9.9968386e-01, 2.0943573e-04,
        6.2185102e-15, 3.1181629e-05, 2.3686770e-08, 1.4294024e-11,
        3.2433567e-07, 2.7188575e-12],
       [1.3394551e-06, 9.9584973e-01, 2.8113229e-04, 4.6837373e-05,
        3.3391541e-05, 1.1930831e-05, 2.3197550e-05, 3.4036413e-03,
        3.4762794e-04, 1.1245446e-06],
       [9.9980074e-01, 1.2037691e-09, 1.3226480e-05, 4.9340533e-06,
        3.4407731e-07, 5.1972138e-06, 8.0272061e-05, 7.9112469e-05,
        4.7962517e-06, 1.1446761e-05],
       [3.7092400e-06, 2.7891986e-07, 5.4125562e-06, 4.9147110e-07,
        9.8989946e-01, 5.9671100e-07, 4.6136071e-07, 6.0657920e-05,
        2.0659961e-06, 1.0026795e-02]], dtype=float32)>

Conclusion
Congratulations! You have trained a machine learning model using a prebuilt dataset using the Keras API.